name: Markdownlint

on:
  push:
    paths:
      - "**/*.md"
  pull_request:
    paths:
      - "**/*.md"

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #@v2
    - name: Use Node.js
      uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b #@v1
      with:
        node-version: 12.x
    - name: Run Markdownlint
      run: |
        npm i -g markdownlint-cli@0.22.0
        markdownlint "**/*.md"
